[theme]

# The preset Streamlit theme that your custom theme inherits from.
# This can be one of the following: "light" or "dark".
base = "light"

[client]
toolbarMode = "minimal"

[server]
enableCORS = false
enableXsrfProtection = false